version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:latest
    steps:
      - checkout
      - run:
          name: install awesome bot
          command: gem install awesome_bot
      - run:
          name: check readme links
          command: awesome_bot README.md --allow-redirect
